version: '3.8'
services:
  tester:
    image: alpine
    command: tail -f /dev/null
    networks:
      - vpnnet
      - appnet2
      - appnet3
      - dbnet

networks:
  vpnnet:
    external: true
  appnet2:
    external: true
  appnet3:
    external: true
  dbnet:
    external: true
