#!/bin/bash
"""
Backend Service Discovery Script for HAProxy
Discovers services in the proxy-network and generates backend configurations
"""

set -euo pipefail

# Configuration
NETWORK_NAME="proxy-network"
CONFIG_DIR="/usr/local/etc/haproxy"
BACKEND_CONFIG_FILE="$CONFIG_DIR/backends-discovered.cfg"
DOCKER_SOCKET="/var/run/docker.sock"

# Logging function
log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" >&2
}

# Check if Docker socket is available
check_docker_access() {
    if [[ ! -S "$DOCKER_SOCKET" ]]; then
        log "ERROR: Docker socket not available at $DOCKER_SOCKET"
        return 1
    fi
    
    if ! docker info >/dev/null 2>&1; then
        log "ERROR: Cannot connect to Docker daemon"
        return 1
    fi
    
    log "Docker access confirmed"
    return 0
}

# Discover services in the proxy-network
discover_services() {
    log "Discovering services in network: $NETWORK_NAME"
    
    # Get all containers connected to the proxy-network
    local containers
    containers=$(docker network inspect "$NETWORK_NAME" --format '{{range .Containers}}{{.Name}} {{.IPv4Address}}{{"\n"}}{{end}}' 2>/dev/null || echo "")
    
    if [[ -z "$containers" ]]; then
        log "No containers found in network $NETWORK_NAME"
        return 1
    fi
    
    echo "$containers"
}

# Generate backend configuration for a service
generate_backend_config() {
    local service_name="$1"
    local ip_address="$2"
    local port="${3:-80}"
    
    # Extract service type from container name patterns
    local backend_name=""
    local health_path="/health"
    local weight="100"
    
    case "$service_name" in
        *root*|*main*)
            backend_name="root_backend"
            ;;
        *www*)
            backend_name="www_backend"
            ;;
        *api*)
            backend_name="api_backend"
            health_path="/api/health"
            ;;
        *app*)
            backend_name="app_backend"
            health_path="/app/health"
            ;;
        *admin*)
            backend_name="admin_backend"
            health_path="/admin/health"
            weight="50"
            ;;
        *demo*)
            backend_name="demo_backend"
            health_path="/demo/health"
            ;;
        *)
            backend_name="default_backend"
            ;;
    esac
    
    # Generate server line
    echo "    server ${service_name} ${ip_address%/*}:${port} check weight ${weight}"
}

# Update HAProxy configuration with discovered backends
update_haproxy_config() {
    local discovered_services="$1"
    
    log "Updating HAProxy configuration with discovered services"
    
    # Create temporary backend configuration
    local temp_config
    temp_config=$(mktemp)
    
    cat > "$temp_config" << 'EOF'
# Auto-generated backend server configurations
# Generated by backend-discovery.sh
# DO NOT EDIT MANUALLY - This file is automatically updated

EOF
    
    # Process each discovered service
    while IFS=' ' read -r service_name ip_address; do
        if [[ -n "$service_name" && -n "$ip_address" ]]; then
            # Skip HAProxy container itself
            if [[ "$service_name" == *"haproxy"* ]]; then
                continue
            fi
            
            log "Found service: $service_name at $ip_address"
            
            # Detect service port (default to 80)
            local port="80"
            if [[ "$service_name" == *"api"* ]]; then
                port="8080"
            elif [[ "$service_name" == *"admin"* ]]; then
                port="8443"
            elif [[ "$service_name" == *"app"* ]]; then
                port="3000"
            fi
            
            # Generate configuration
            generate_backend_config "$service_name" "$ip_address" "$port" >> "$temp_config"
        fi
    done <<< "$discovered_services"
    
    # Move temporary config to final location
    mv "$temp_config" "$BACKEND_CONFIG_FILE"
    
    log "Backend configuration updated: $BACKEND_CONFIG_FILE"
}

# Validate HAProxy configuration
validate_config() {
    log "Validating HAProxy configuration"
    
    if haproxy -c -f "$CONFIG_DIR/haproxy.cfg" >/dev/null 2>&1; then
        log "HAProxy configuration is valid"
        return 0
    else
        log "ERROR: HAProxy configuration validation failed"
        return 1
    fi
}

# Reload HAProxy configuration
reload_haproxy() {
    log "Reloading HAProxy configuration"
    
    # Send SIGUSR2 to HAProxy master process for graceful reload
    local haproxy_pid
    haproxy_pid=$(pgrep -f "haproxy.*master" || echo "")
    
    if [[ -n "$haproxy_pid" ]]; then
        kill -USR2 "$haproxy_pid"
        log "HAProxy reload signal sent to PID: $haproxy_pid"
    else
        log "WARNING: HAProxy master process not found"
    fi
}

# Main function
main() {
    log "Starting backend service discovery"
    
    # Check prerequisites
    if ! check_docker_access; then
        exit 1
    fi
    
    # Create config directory if it doesn't exist
    mkdir -p "$CONFIG_DIR"
    
    # Discover services
    local services
    if services=$(discover_services); then
        # Update configuration
        update_haproxy_config "$services"
        
        # Validate and reload if configuration is valid
        if validate_config; then
            reload_haproxy
            log "Backend discovery completed successfully"
        else
            log "ERROR: Configuration validation failed, not reloading"
            exit 1
        fi
    else
        log "No services discovered, creating empty backend configuration"
        echo "# No services discovered" > "$BACKEND_CONFIG_FILE"
    fi
}

# Handle script arguments
case "${1:-}" in
    --discover-only)
        discover_services
        ;;
    --validate-only)
        validate_config
        ;;
    --help|-h)
        echo "Usage: $0 [--discover-only|--validate-only|--help]"
        echo "  --discover-only: Only discover services, don't update config"
        echo "  --validate-only: Only validate current HAProxy config"
        echo "  --help: Show this help message"
        ;;
    *)
        main
        ;;
esac