server.memory.heap.initial_size=512m
server.memory.heap.max_size=512m
server.memory.pagecache.size=512m
dbms.usage_report.enabled=false
dbms.connector.bolt.enabled=true
server.directories.plugins=/plugins
server.directories.import=/import
server.directories.logs=/logs  
client.allow_telemetry=false
server.jvm.additional=-Djol.skipHotspotSAAttach=true #GDS setting
